query WotSearchByText($searchText: String!, $first: Int!, $after: String, $orderBy: [AccountOrderBy!]) {
  accountConnection(
    first: $first
    after: $after
    orderBy: $orderBy
    where: { _or: [{ id: { _ilike: $searchText } }, { identity: { name: { _ilike: $searchText } } }] }
  ) {
    ...LightAccountConnection
  }
}

query WotSearchByAddress($address: String!, $first: Int!, $after: String, $orderBy: [AccountOrderBy!]) {
  accountConnection(first: $first, after: $after, orderBy: $orderBy, where: { id: { _eq: $address } }) {
    ...LightAccountConnection
  }
}

query WotSearchLast($first: Int!, $after: String, $orderBy: [AccountOrderBy!], $pending: Boolean!) {
  accountConnection(
    first: $first
    after: $after
    orderBy: $orderBy
    where: { _and: [{ identity: { id: { _isNull: false } } }, { identity: { membershipHistory: { eventId: { _isNull: $pending } } } }] }
  ) {
    ...LightAccountConnection
  }
}

# search identities by exact name
query WotSearchByUid($name: String!, $first: Int!, $after: String, $orderBy: [AccountOrderBy!]) {
  accountConnection(first: $first, after: $after, orderBy: $orderBy, where: { identity: {name: { _eq: $name } }}) {
    ...LightAccountConnection
  }
}
