fragment LightBlock on Block {
  id
  height
  hash
  timestamp
  callsCount
  eventsCount
  extrinsicsCount
  __typename
}
fragment LightBlockConnection on BlockConnection {
  pageInfo {
    endCursor
    hasNextPage
  }
  edges {
    node {
      ...LightBlock
    }
  }
}

query BlockById($id: String!) {
  blockConnection(where: { id: { _eq: $id } }) {
    ...LightBlockConnection
  }
}

query Blocks($where: BlockBoolExp, $first: Int!, $after: String, $orderBy: [BlockOrderBy!]) {
  blockConnection(first: $first, after: $after, orderBy: $orderBy, where: $where) {
    ...LightBlockConnection
  }
}

query LastBlock {
  blockConnection(first: 1, orderBy: { height: DESC }) {
    ...LightBlockConnection
  }
}
