# ---------------------------------------------------------------
# Global
# ---------------------------------------------------------------

# default image
image: node:18-slim

stages:
  - environment
  - build
  - alt_build
  - release
  - deploy

workflow:
  rules:
    - changes:
        - docker/**/Dockerfile
        - src/**/*
        - android/**/*
        - .gitlab-ci.yml
        - package.json
        - package-lock.json
        - tsconfig*.json
        - angular.json

# ---------------------------------------------------------------
# Global variables
# ---------------------------------------------------------------

variables:
  CI_BUILD_IMAGE: $CI_REGISTRY_IMAGE/build:develop
  BUILD_CACHE_DIR: /tmp/.build-cache
  BUILD_ENVIRONMENT: prod
  DOCKER_BUILDKIT: 1
  ARTIFACT_ZIP_FILES: ${OUTPUT_DIR}/${CI_PROJECT_NAME}-*.zip
  ENV_FILE: variables.env
  IONIC_CLI_VERSION: 7.2.0
  ANGULAR_CLI_VERSION: 17.0.3

# ---------------------------------------------------------------
# Jobs templates
# ---------------------------------------------------------------
.configure-git-template: &git-setup
  tags: [kepler]
  before_script:
    - echo "--- Fetch origin"
    - git remote set-url origin "https://gitlab+access-token:${CI_ACCESS_TOKEN}@git.duniter.org/${CI_PROJECT_PATH}.git"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git fetch origin

.docker:
  image: docker:latest
  tags: [kepler]
  services:
    - docker:dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  after_script:
    - docker logout ${CI_REGISTRY}
  allow_failure: false

# ---------------------------------------------------------------
# Environment jobs : Create docker image for builds/release, this
# offers possibility to cache project dependencies so we don't
# have to download them every time.
# ---------------------------------------------------------------
build:env:
  extends: .docker
  stage: environment
  script:
    # Build and push the CI image
    - docker build --cache-from ${CI_BUILD_IMAGE} -t ${CI_BUILD_IMAGE} --build-arg="BUILDKIT_INLINE_CACHE=1" --build-arg="CACHE_DIR=${BUILD_CACHE_DIR}" --build-arg="IMAGE_REGISTRY=${DOCKER_IMAGE_REGISTRY}" --build-arg="IONIC_CLI_VERSION=${IONIC_CLI_VERSION}" --build-arg="ANGULAR_CLI_VERSION=${ANGULAR_CLI_VERSION}" -f docker/build/Dockerfile .
    - docker push ${CI_BUILD_IMAGE}
  except:
    - tags
    - master
  only:
    - develop
  when: manual

# ---------------------------------------------------------------
# Build jobs
# ---------------------------------------------------------------
.build:
  stage: build
  tags: [kepler]
  before_script:
    # Get project dependencies
    - ls -artl ${BUILD_CACHE_DIR}
    - cp -R ${BUILD_CACHE_DIR}/node_modules .
    # Before command
    - ${BEFORE_SCRIPT}
  script:
    # Build
    - npm run build:${BUILD_ENVIRONMENT}
  after_script:
    # Remember version
    - APP_VERSION=$(node -e "console.log(require('./package.json').version)")
    - echo "APP_VERSION=${APP_VERSION}" > ${ENV_FILE}
  artifacts:
    paths:
      - www
    reports:
      dotenv: ${ENV_FILE}
    expire_in: 72 hours
  variables:
    BEFORE_SCRIPT: npm version

build:
  extends: .build
  needs: ["build:env"]
  image: ${CI_BUILD_IMAGE}
  only:
    - develop

build:feature:
  extends: .build
  image: ${CI_BUILD_IMAGE}
  variables:
    BEFORE_SCRIPT: npm install
  only:
    - /^feature\/.*/
    - /^features\/.*/
  when: manual

build:android:
  extends: .build
  image: ${CI_BUILD_IMAGE}
  before_script:
    # Get project dependencies
    - ln -s "${BUILD_CACHE_DIR}/node_modules" /build/node_modules
    # Install Android environment (e.g. will create local.properties)
    - echo "--- Create Android 'local.properties' ..."
    - echo 'sdk.dir=/root/Android/Sdk' > android/local.properties
    # Prepare for signing
    - echo "--- Preparing Android 'release-signing.properties' file ..."
    - echo 'storeFile=Cesium.keystore' > android/app/release-signing.properties
    - echo 'keyAlias=Cesium' >> android/app/release-signing.properties
    - echo 'storePassword=${ANDROID_STORE_PASSWORD}' >> android/app/release-signing.properties
    - echo 'keyPassword=${ANDROID_KEY_PASSWORD}' >> android/app/release-signing.properties
  script:
    # Build APK
    - npm run android:build:${BUILD_ENVIRONMENT}
  after_script:
    # Make APK file available for next jobs
    - mkdir -p "${CI_PROJECT_DIR}/release/"
    - cp ${CI_PROJECT_DIR}/android/app/build/outputs/apk/*/.apk $CI_PROJECT_DIR/release/
  variables:
    BEFORE_SCRIPT: npm run android:install
  artifacts:
    paths:
      - $CI_PROJECT_DIR/release/
    reports:
      dotenv: ${ENV_FILE}
    expire_in: 72 hours
  only:
    - develop
    #- /^feature\/.*/
    #- /^features\/.*/
  #when: manual

failsafe-build:
  extends: .build
  stage: alt_build
  when: on_failure
  before_script:
    # Install global dependencies
    - npm install -g @ionic/cli@${IONIC_CLI_VERSION} @angular/cli@${ANGULAR_CLI_VERSION}
    # Update project dependencies
    - npm install --unsafe-perm --force
  only:
    - develop
    - /^feature\/.*/
    - /^features\/.*/

# ---------------------------------------------------------------
# Release jobs
# ---------------------------------------------------------------
.release:
  <<: *git-setup
  stage: release
  script:
    - if [[ "_${RELEASE_VERSION}" == "_" ]]; then exit 1; fi
    - echo "--- Release in progress"
    - git checkout -B release/${RELEASE_VERSION}
    - echo "--- Manage app version"
    - 'current=$(grep -oP "version\": \"\d+.\d+.\d+(-(alpha|beta|rc)[0-9]+)?" package.json | grep -m 1 -oP "\d+.\d+.\d+(-(alpha|beta|rc)[0-9]+)?")'
    - 'currentManifestVersion=$(grep -oP "version\": \"\d+.\d+.\d+(-(alpha|beta|rc)[0-9]+)?\"" src/manifest.json | grep -oP "\d+.\d+.\d+(-(alpha|beta|rc)[0-9]+)?")'
    - 'currentAndroidVersionCode=$(grep -oP "versionCode [0-9]+" android/app/build.gradle | grep -oP "\d+")'
    - 'currentAndroidVersionName=$(grep -oP "versionName \"\d+.\d+.\d+(-(alpha|beta|rc)[0-9]+)?\"" android/app/build.gradle | grep -oP "\d+.\d+.\d+(-(alpha|beta|rc)[0-9]+)?")'
    - 'echo " Current version: $current"'
    - 'echo " Current Manifest version: $currentManifestVersion"'
    - 'echo " Current Android version code: $currentAndroidVersionCode"'
    - 'echo " Current Android version name: $currentAndroidVersionName"'
    - 'IFS="."'
    - 'read -ra SPLITED_VERSION <<< "${RELEASE_VERSION}"'
    - 'IFS="-"'
    - 'read -ra SPLITED_PATCH <<< "${SPLITED_VERSION[2]}"'
    - 'major2d=$(printf %02d ${SPLITED_VERSION[0]}) ; minor2d=$(printf %02d ${SPLITED_VERSION[1]}) ; patch2d=$(printf %02d ${SPLITED_PATCH[0]})'
    - 'androidVersionCode=$major2d$minor2d$patch2d'
    - 'echo " Next version: ${RELEASE_VERSION}"'
    - 'echo " Next Android version code: $androidVersionCode"'
    - 'sed -i "s/\"version\": \"$current\"/\"version\": \"${RELEASE_VERSION}\"/g" package.json'
    - 'sed -i "s/\"version\": \"$currentManifestVersion\"/\"version\": \"${RELEASE_VERSION}\"/g" src/manifest.json'
    - 'sed -i "s/versionCode $currentAndroidVersionCode\"/versionCode $androidVersionCode\"/g" android/app/build.gradle'
    - 'sed -i "s/versionName \"$currentAndroidVersionName\"/versionName \"${RELEASE_VERSION}\"/g" android/app/build.gradle'
    - 'sed -i "s/echo \".*\" #lastest/echo \"${RELEASE_VERSION}\" #lastest/g" install.sh'
    # Copy cached dependencies and build
    - ls -artl "${BUILD_CACHE_DIR}"
    - cp -R "${BUILD_CACHE_DIR}/node_modules" .
    # Show version
    - npm version
    - export NODE_OPTIONS=--max-old-space-size=4096
    # Build web (if need)
    - echo "--- Building 'www'"
    - if [[ "$BUILD_ENVIRONMENT" != "prod" || ! -d "www" ]]; then npm run build:prod; fi
    # Git process for release (ISO gitflow)
    - echo "--- Fishing release"
    - git add package.json src/manifest.json android/app/build.gradle install.sh
    - git commit -m "Prepare release ${RELEASE_VERSION}" --no-verify
    - git checkout master
    - git reset --hard origin/master
    - git merge --no-ff --no-edit -m "Release ${RELEASE_VERSION}" "release/${RELEASE_VERSION}"
    - git tag -a "${RELEASE_VERSION}" -m "${RELEASE_VERSION}"
    - git checkout ${CI_COMMIT_REF_NAME}
    - git reset --hard origin/${CI_COMMIT_REF_NAME}
    - git merge --no-ff --no-edit -m "[skip ci] Release ${RELEASE_VERSION}" "release/${RELEASE_VERSION}"
    - git push origin ${CI_COMMIT_REF_NAME}
    - git push origin master
    - git push --tags
    - git branch -D "release/${RELEASE_VERSION}"
  after_script:
    # Remember version
    - APP_VERSION=${RELEASE_VERSION}
    - echo "APP_VERSION=${APP_VERSION}" > ${ENV_FILE}
    - mkdir -p ${CI_PROJECT_DIR}/release
    # Zip output
    - fileName=${CI_PROJECT_NAME}-${APP_VERSION}.zip
    - zipFile=${CI_PROJECT_DIR}/release/${fileName}
    - if [[ -f "${zipFile}" ]]; then rm "${zipFile}"; fi
    - cd ${CI_PROJECT_DIR}/www || exit 1
    - if ! zip -q -r "${zipFile}" . ; then echo "Cannot create the archive for the web artifact"; exit 1; fi
    - cd ${CI_PROJECT_DIR}
    - targetUrl="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${APP_VERSION}/${fileName}"
    - echo "Deploy to gitlab generic package :"
    - echo " File= ${zipFile}"
    - echo " Url= ${targetUrl}"
    - 'if ! curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "${zipFile}" "${targetUrl}"; then exit 1; fi'
    # APK output
    #- fileName=${CI_PROJECT_NAME}-${APP_VERSION}-android.apk
    #- apkFile=${CI_PROJECT_DIR}/release/app-release.apk
    #- targetUrl="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${APP_VERSION}/${apkFile}"
    #- echo "Deploy to gitlab generic package :"
    #- echo " File= ${apkFile}"
    #- echo " Url= ${targetUrl}"
    #- 'if ! curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "${apkFile}" "${targetUrl}"; then exit 1; fi'
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/release
    reports:
      dotenv: ${ENV_FILE}
    expire_in: 24 hours
  allow_failure: false
  only:
    - develop
  when: manual

release:
  extends: .release
  image: ${CI_BUILD_IMAGE}
  needs: [build]

failsafe-release:
  extends: .release
  needs: [failsafe-build]

release:tags:
  <<: *git-setup
  image: ${CI_BUILD_IMAGE}
  stage: release
  script:
    - echo "--- Release in progress"
    - git checkout -b release/${CI_COMMIT_TAG}
    # Copy cached dependencies and build
    - ls -artl "${BUILD_CACHE_DIR}"
    - cp -R "${BUILD_CACHE_DIR}/node_modules" .
    # Show version
    - npm version
    # Build
    - export NODE_OPTIONS=--max-old-space-size=4096
    - npm run build:prod
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/release
    # Zip output
    - fileName=${CI_PROJECT_NAME}-${APP_VERSION}.zip
    - zipFile=${CI_PROJECT_DIR}/release/${fileName}
    - if [[ -f "${zipFile}" ]]; then rm "${zipFile}"; fi
    - cd ${CI_PROJECT_DIR}/www || exit 1
    - if ! zip -q -r "${zipFile}" . ; then echo "Cannot create the archive for the web artifact"; exit 1; fi
    - cd ..
    - targetUrl="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${APP_VERSION}/${fileName}"
    - echo "Deploy to gitlab generic package :"
    - echo " File= ${zipFile}"
    - echo " Url= ${targetUrl}"
    - 'if ! curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "${zipFile}" "${targetUrl}"; then exit 1; fi'
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/release
    expire_in: 24 hours
  allow_failure: false
  when: manual
  only:
    - tags


gitlab-release:
  stage: release
  tags: [kepler]
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "running release for ${CI_COMMIT_TAG}"
  release:
    name: "Release ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
    description: "Created using the release-cli $EXTRA_DESCRIPTION"
    tag_name: "${CI_COMMIT_TAG}"
    ref: "${CI_COMMIT_TAG}"
  only:
    - tags

# ---------------------------------------------------------------
# Deploy jobs
# ---------------------------------------------------------------
deploy:android:
  image: ${CI_BUILD_IMAGE}
  stage: deploy
  needs: [release]
  before_script:
    # Install Android environment (e.g. will create local.properties)
    - echo "--- Create Android 'local.properties' ..."
    - echo 'sdk.dir=/root/Android/Sdk' > android/local.properties
    # Prepare for signing
    - echo "--- Preparing Android 'release-signing.properties' file ..."
    - echo 'storeFile=Cesium.keystore' > android/app/release-signing.properties
    - echo 'keyAlias=Cesium' >> android/app/release-signing.properties
    - echo 'storePassword=${ANDROID_STORE_PASSWORD}' >> android/app/release-signing.properties
    - echo 'keyPassword=${ANDROID_KEY_PASSWORD}' >> android/app/release-signing.properties
  script:
    # APK output
    - buildApkFile="${CI_PROJECT_DIR}/android/app/build/outputs/apk/release/app-release.apk"
    - if [[ ! -f "${buildApkFile}" ]]; then npm run android:build:prod; fi
    - fileName=${CI_PROJECT_NAME}-${APP_VERSION}-android.apk
    - apkFile=${CI_PROJECT_DIR}/release/${fileName}
    - cp "${buildApkFile}" "${apkFile}"
    - targetUrl="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${APP_VERSION}/${fileName}"
    - echo "Deploy to gitlab APK package :"
    - echo " File= ${apkFile}"
    - echo " Url= ${targetUrl}"
    - 'if ! curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "${apkFile}" "${targetUrl}"; then exit 1; fi'
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/release
    expire_in: 24 hours
  allow_failure: true
