schema: src/schema.graphql
extensions:
  endpoints:
    Gdev GraphQL Endpoint:
      url: https://subsquid.gdev.coinduf.eu/graphql
      headers:
        user-agent: JS GraphQL
      introspect: false
